services:
  api:
    container_name: api
    build: 
      context: ./api
      target: base
    image: argon/api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app:cached
    working_dir: /app
  web:
    container_name: web
    build: 
      context: ./web
      target: base
    image: argon/web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app:cached
    environment:
      - REACT_APP_API_SERVER=http://localhost:8080/api
    working_dir: /app
